export const videos = [
  {
    loc: "/banjo-videoanleitung/",
    title: "Flint Hill Special - Banjo Lesson",
    description: "Lerne das Banjostück 'Flint Hill Special von Earl Scruggs'. Es wird in dem Stück ein sogenannter D-Tuner verwendet. Ich erkläre genau wie man so einen D-Tuner benutzt und einstellt.",
    thumbnail_loc: "https://i.ytimg.com/vi/R75ZetEwmtw/hqdefault.jpg",
    content_loc: "https://www.youtube.com/embed/R75ZetEwmtw",
    publication_date: "2023-06-17T14:00:00+02:00",
    duration: "812",
  },
  {
    loc: "/banjo-videoanleitung/",
    title: "Train 45 - Bluegrass Banjo",
    description: "Lerne das Banjostück Train 45 - Bluegrass Banjo.",
    thumbnail_loc: "https://i.ytimg.com/vi/uo5ojnmRHPo/hqdefault.jpg",
    content_loc: "https://www.youtube.com/embed/uo5ojnmRHPo",
    publication_date: "2023-05-26T14:00:00+02:00",
    duration: "391",
  },
  {
    loc: "/banjo-videoanleitung/",
    title: "Banjo Beginner Lesson 2",
    description: "Lerne das Banjostück 'Cripple Creek'. Mit diesem Stück hat Earl Scruggs als kleiner Junge schon einen Preis gewonnen.",
    thumbnail_loc: "https://i.ytimg.com/vi/WmYlSqvpUkw/hqdefault.jpg",
    content_loc: "https://www.youtube.com/embed/WmYlSqvpUkw",
    publication_date: "2023-04-05T14:00:00+02:00",
    duration: "556",
  },
  {
    loc: "/klavier-videoanleitung/",
    title: "PRAELUDIUM BMV 927 - Johann Sebastian Bach",
    description: "Klassisches Klavierstück auswendig lernen! Für mich ist dies eins der schwierigsten Dinge. Dieses Stück hat nur eine Seite, da geht es noch einigermaßen.",
    thumbnail_loc: "https://i.ytimg.com/vi/vxX0WiQhSUE/hqdefault.jpg",
    content_loc: "https://www.youtube.com/embed/vxX0WiQhSUE",
    publication_date: "2021-05-20T14:00:00+02:00",
    duration: "154",
  },
  {
    loc: "/klavier-videoanleitung/",
    title: "Aus der neuen Welt - Antonin Dvorak",
    description: "Klavier Tutorial für das klassische Stück von Antonin Dvorak. Ich spiele hier nur der zweiten Satz das 'Largo'. Antonin Dvorak hat es für Orchester aber auch für Klavier zu vier Händen geschrieben. Ich habe es für 2 Händen umgeschrieben.",
    thumbnail_loc: "https://i.ytimg.com/vi/ytcQ-I1BTNk/hqdefault.jpg",
    content_loc: "https://www.youtube.com/embed/ytcQ-I1BTNk",
    publication_date: "2021-04-21T00:00:00+02:00",
    duration: "779",
  },
  {
    loc: "/e-gitarre-videoanleitung/",
    title: "Joe Satriani - Ten Words Guitar Lesson+Tab",
    description: "Lerne das Gitarrenstück 'Ten Words' von Joe Satriani mit dieser detaillierten Gitarrenstunde. Falls jemand das Stück lernen möchte mir eine E-Mail schreiben. Ich helfe dann weiter!",
    thumbnail_loc: "https://i.ytimg.com/vi/fcHrj9ryvqo/hqdefault.jpg",
    content_loc: "https://www.youtube.com/embed/fcHrj9ryvqo",
    publication_date: "2025-04-21T14:00:00+02:00",
    duration: "239",
  },
  {
    loc: "/e-gitarre-videoanleitung/",
    title: "Take Good Care Of My Baby - Bobby Vee Cover",
    description: "Lerne das Gitarrenstück 'Take Good Care Of My Baby' von Bobby Vee mit dieser detaillierten Gitarrenstunde.",
    thumbnail_loc: "https://i.ytimg.com/vi/nUC_b1L_IM4/hqdefault.jpg",
    content_loc: "https://www.youtube.com/embed/nUC_b1L_IM4",
    publication_date: "2025-01-04T14:00:00+02:00",
    duration: "1072",
  },
  {
    loc: "/e-gitarre-videoanleitung/",
    title: "Christmas Time Is Here – Jazzguitar Lesson (Jazz Gitarren-Tutorial)",
    description: "Lerne das leichte Jazzgitarrenstück 'Christmas Time Is Here' mit diesem Video. Die Tabulatur kann man unten in der Viedeobeschreibung downloaden.",
    thumbnail_loc: "https://i.ytimg.com/vi/5StMXBTQGpw/hqdefault.jpg",
    content_loc: "https://www.youtube.com/embed/5StMXBTQGpw",
    publication_date: "2025-12-03T14:00:00+02:00",
    duration: "58",
  },
  {
    loc: "/e-gitarre-videoanleitung/",
    title: "Smile (Charlie Chaplin) – Jazz Guitar Lesson | Melodic Style",
    description: "Lerne das leichte Jazzgitarrenstück 'Smile (Charlie Chaplin)' mit diesem Video. Die Tabulatur kann man unten in der YouTube Viedeobeschreibung downloaden.",
    thumbnail_loc: "https://i.ytimg.com/vi/gVWldWICw6U/hqdefault.jpg",
    content_loc: "https://www.youtube.com/embed/gVWldWICw6U",
    publication_date: "2025-12-31T14:00:00+02:00",
    duration: "434",
  },
  {
    loc: "/e-gitarre-videoanleitung/",
    title: "🎸 Rose Room – Charlie Christian Guitar Solo (Jazz Guitar Lesson & Transcription)",
    description: "Lerne das leichte Jazzgitarrenstück 'Rose Room (Charlie Christian)' mit diesem Video. Die Tabulatur kann man unten in der YouTube Viedeobeschreibung downloaden.",
    thumbnail_loc: "https://i.ytimg.com/vi/gVWldWICw6U/hqdefault.jpg",
    content_loc: "https://www.youtube.com/embed/gVWldWICw6U",
    publication_date: "2025-12-31T14:00:00+02:00",
    duration: "434",
  },
  {
    loc: "/gitarre-videoanleitung/",
    title: "Silence Is Golden – The Tremeloes – Guitar Lesson (Gitarren-Tutorial)",
    description: "Willkommen zu meinem Gitarren-Tutorial zu “Silence Is Golden” von The Tremeloes! In diesem Video zeige ich dir Schritt für Schritt, wie du den Song auf der Akustikgitarre spielen kannst",
    thumbnail_loc: "https://i.ytimg.com/vi/OxBca9ZfFv8/hqdefault.jpg",
    content_loc: "https://www.youtube.com/embed/OxBca9ZfFv8",
    publication_date: "2025-11-25T14:23:00+02:00",
    duration: "739",
  },
  {
    loc: "/gitarre-videoanleitung/",
    title: "🎸 The Lion Sleeps Tonight – Gitarren-Tutorial (einfach erklärt)",
    description: "Lerne den bekannten Song 'The Lion Sleeps Tonight' Schritt für Schritt auf der Gitarre! 🎶 In diesem Gitarren-Tutorial zeige ich dir alle Akkorde, Schlagmuster und Rhythmusvarianten, damit du den Song allein auf der Gitarre spielen kannst – ohne Playback oder Begleitung. Ich spiele den Song zunächst mit meinem eigenen Playback vor, damit du hörst, wie er komplett klingt, und erkläre danach alle Teile einzeln, damit du ihn selbst spielen kannst. 🎧 Hinweis: Das Playback wird nur für die Demonstration verwendet – du lernst den Song so, dass du ihn komplett allein auf der Gitarre spielen kannst.",
    thumbnail_loc: "https://i.ytimg.com/vi/eFcGadGwenQ/hqdefault.jpg",
    content_loc: "https://www.youtube.com/embed/eFcGadGwenQ",
    publication_date: "2025-10-29T14:23:00+02:00",
    duration: "775",
  },
  {
    loc: "/gitarre-videoanleitung/",
    title: "Like Ice In The Sunshine – New Mix – Guitar Lesson (Gitarren-Tutorial)",
    description: "In diesem Video zeige ich dir, wie du Like Ice In The Sunshine auf der Gitarre spielen kannst. Du lernst Schritt für Schritt die Akkorde, den Rhythmus und den Schlag. Ideal für Anfänger, Fortgeschrittente und alle, die diesen bekannten Popsong auf der Akustikgitarre spielen möchten.",
    thumbnail_loc: "https://i.ytimg.com/vi/Jk6ECVwJyZk/hqdefault.jpg",
    content_loc: "https://www.youtube.com/embed/Jk6ECVwJyZk",
    publication_date: "2025-08-30T14:23:00+02:00",
    duration: "792",
  },
  {
    loc: "/gitarre-videoanleitung/",
    title: "Beatles – Yesterday | Gitarre Tutorial 🎸",
    description: "Lernevideo und Gitarrentutorial für das Gitarrenstück 'Yesterday von den Beatles'. Dieses Stück kann man wunderbar alleine spielen, also ohne Bass, Drums usw. Die Gitarre wird in einer Double Flatstimmung umgestimmt.",
    thumbnail_loc: "https://i.ytimg.com/vi/Jla_18ar1aE/hqdefault.jpg",
    content_loc: "https://www.youtube.com/embed/Jla_18ar1aE",
    publication_date: "2025-09-10T14:00:00+02:00",
    duration: "760",
  },
  {
    loc: "/gitarre-videoanleitung/",
    title: "Catch The Wind – Donovan | Gitarren Tutorial",
    description: "🎸 Lerne „Catch The Wind“ von Donovan auf der Gitarre – Schritt für Schritt erklärt! In diesem Gitarren-Tutorial spiele ich dir den Song komplett vor – begleitet von einem selbst erstellten Playback. Danach erkläre ich dir alle Akkorde, Schlagmuster und die Struktur, damit du den Song selbst begleiten kannst. 📌 Die Version basiert auf der Aufnahme von Donovan aus dem Jahr 1965 – ich habe sie nach Gehör herausgearbeitet. ✅ Inhalt: • Komplettes Vorspiel mit Playback • Einfache Akkorde & Schlagmuster • Songabschnitte verständlich erklärt",
    thumbnail_loc: "https://i.ytimg.com/vi/ifJuoPeWBU8/hqdefault.jpg",
    content_loc: "https://www.youtube.com/embed/ifJuoPeWBU8",
    publication_date: "2025-09-16T14:00:00+02:00",
    duration: "1488",
  },
  {
    loc: "/keyboard-videoanleitung/",
    title: "Hammond Organ - Hammond Flip - Klaus Wunderlich",
    description: "Keyboard Tutorial über eine Klaus Wunderlich Komposition. Das Stück heißt 'Hammond Flip'.",
    thumbnail_loc: "https://i.ytimg.com/vi/y2KtSx3-W3w/hqdefault.jpg",
    content_loc: "https://www.youtube.com/embed/244HlpB3JoA",
    publication_date: "2021-07-08T14:00:00+02:00",
    duration: "186",
  },
  {
    loc: "/keyboard-videoanleitung/",
    title: "Hammond Organ Komponist: Klaus Wunderlich Titel: H-schisch",
    description: "Ein Keyboard Tutorial über den Komponist Klaus Wunderlich. Das Stück das ich spiele heißt 'H-schisch'. Das ist in einem Notenheft von ihm mit 12 Kompositionen. Klaus Wunderlich brachte ein Notenbuch heraus mit 12 Kompositionen von ihm. Für jede Tonart komponierte er ein Stück. Ich habe das Stück in H Durgewählt. Ich habe es mit einem HAMMOND XM-1 Expander aufgenommen.",
    thumbnail_loc: "https://i.ytimg.com/vi/dEih42vJn2M/hqdefault.jpg",
    content_loc: "https://www.youtube.com/embed/dEih42vJn2M",
    publication_date: "2025-04-22T14:00:00+02:00",
    duration: "256",
  },
  {
    loc: "/keyboard-videoanleitung/",
    title: "Hammond Organ Komponist: Klaus Wunderlich Titel: E-Hering",
    description: "Noch ein Stück aus dem Heft 12 Kompositionen von Klaus Wunderlich. Ein Keyboard Tutorial über den Komponisten Klaus Wunderlich. Titel: E-Hering.",
    thumbnail_loc: "https://i.ytimg.com/vi/dQVFo8bhVSU/hqdefault.jpg",
    content_loc: "https://www.youtube.com/embed/dQVFo8bhVSU",
    publication_date: "2025-04-21T14:00:00+02:00",
    duration: "338",
  },
  {
    loc: "/keyboard-videoanleitung/",
    title: "Hammond Organ - Intermezzo",
    description: "Ich habe vor langer Zeit einmal eine Studioaufnahme mit einer Hammond Orgel A 100 gemacht und ich wollte einmal ein Video darüber machen. Das Stück ist eine Eigenkomposition und ich habe es 'Intermezzo' genannt. Die Noten sind als PDF verfügbar unter /bilder/Intermezzo.pdf",
    thumbnail_loc: "https://i.ytimg.com/vi/D3X3lxcn780/hqdefault.jpg",
    content_loc: "https://www.youtube.com/embed/D3X3lxcn780",
    publication_date: "2021-05-16T14:00:00+02:00",
    duration: "106",
  },
  {
    loc: "/harmonielehre/",
    title: "Notenschrift",
    description: "Ich möchte mit diesem Video die Notenschrift erklären die ja doch so wichtig für die Musik ist! Ich möchte den Schülern, Musikinteressierte oder Hobbymusiker auf diese Weise das Noten lesen und die Harmonielehre ein bisschen näher bringen! Die Videos sind so aufgebaut das man zuerst die Noten lesen kann, dann kommen die Intervalle, dann die Dreiklänge und zuletzt die Funktiontheorie. Also bitte nach der Reihenfolge lernen! Ich werde mit dem ersten Video das Noten lesen erklären.",
    thumbnail_loc: "https://i.ytimg.com/vi/Hu4ef1IkuG0/hqdefault.jpg",
    content_loc: "https://www.youtube.com/embed/Hu4ef1IkuG0",
    publication_date: "2021-04-19T00:00:00+02:00",
    duration: "832",
  },
  {
    loc: "/harmonielehre/",
    title: "Intervalle",
    description: "Ich werde in diesem Video versuchen die Intervalle zu erklären und zu bestimmen. Ein Intervall ist der Tonabstand zweier Töne. Also Prime, Sekunde, Terz, Quarte, Quinte, Sexte, Septime und Oktave.",
    thumbnail_loc: "https://i.ytimg.com/vi/804rrOOFzAQ/hqdefault.jpg",
    content_loc: "https://www.youtube.com/embed/804rrOOFzAQ",
    publication_date: "2023-04-27T00:00:00+02:00",
    duration: "1075",
  },
  {
    loc: "/harmonielehre/",
    title: "Dreiklänge",
    description: "Ich werde in diesem Video versuchen die Dreiklänge besser zu verstehen. Sie sind wichtig da diese zum Beispiel eintscheiden ob ein Akkord ein Durakkord ist oder ein Mollakkord und noch vieles mehr.",
    thumbnail_loc: "https://i.ytimg.com/vi/fgzboODvlQ4/hqdefault.jpg",
    content_loc: "https://www.youtube.com/embed/fgzboODvlQ4",
    publication_date: "2021-05-05T00:00:00+02:00",
    duration: "1244",
  },
  {
    loc: "/harmonielehre/",
    title: "Funktiontheorie",
    description: "Bei der Funktionstheorie geht es haupsächlich darum auf welchen Stufen die Akkorde stehen. Die drei Haupdreiklänge heißen zum Beispiel Tonika, Dominante und Subdominante. Sie liegen auf der I., IV. und V. Stufe.",
    thumbnail_loc: "https://i.ytimg.com/vi/tCkpok099xw/hqdefault.jpg",
    content_loc: "https://www.youtube.com/embed/tCkpok099xw",
    publication_date: "2021-05-10T00:00:00+01:00",
    duration: "742",
  },
  {
    loc: "/akkordeon-videoanleitung/",
    title: "L'accordeon Triste - Frnzösische Akkordeonmusik",
    description: "Lerne das Akkordeonstück 'L'accordeon Triste' von Sergio Castelli. Falls jemand das Stück spielen möchte mir einfach eine E-Mail schreiben. Vielleicht kann ich helfen!",
    thumbnail_loc: "https://i.ytimg.com/vi/Eo5gEGD5t40/hqdefault.jpg",
    content_loc: "https://www.youtube.com/embed/Eo5gEGD5t40",
    publication_date: "2025-04-21T10:00:00+02:00",
    duration: "258",
  },
];
