[build]
command = "npm run build"
base = "ossified-osiris/"
publish = "dist"

[build.environment]
SITE_URL = "tangerine-salmiakki-d5cfaa.netlify.app"

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "SAMEORIGIN"
X-XSS-Protection = "1; mode=block"
Access-Control-Allow-Origin = "tangerine-salmiakki-d5cfaa.netlify.app"
Vary = "Origin"
Timing-Allow-Origin = "tangerine-salmiakki-d5cfaa.netlify.app"
Access-Control-Allow-Methods = "GET,POST,PUT,PATCH,DELETE"
Access-Control-Allow-Credentials = "true"
X-Content-Type-Options = "nosniff"

# CSP-Nonce Plugin aktivieren
[[plugins]]
package = "@netlify/plugin-csp-nonce"

[plugins.inputs]
reportOnly = true  # Testmodus, um nichts zu blockieren
reportUri = "/__csp-violations"  # Optionale Logging-URL
unsafeEval = false  # Falls du eval() nicht brauchst
path = "/*"  # CSP soll auf alle Seiten angewendet werden
excludedPath = ["/admin/*", "*.css", "*.js", "*.svg", "*.jpg", "*.png"]

[[edge_functions]]
function = "csp-nonce"
path = "/*"

