[build]
command = "npm run build"
base = "ossified-osiris/"
publish = "dist"

[build.environment]
SITE_URL = "tangerine-salmiakki-d5cfaa.netlify.app"

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "SAMEORIGIN"
X-XSS-Protection = "1; mode=block"
Access-Control-Allow-Origin = "tangerine-salmiakki-d5cfaa.netlify.app"
Vary = "Origin"
Timing-Allow-Origin = "tangerine-salmiakki-d5cfaa.netlify.app"
Access-Control-Allow-Methods = "GET,POST,PUT,PATCH,DELETE"
Access-Control-Allow-Credentials = "true"
X-Content-Type-Options = "nosniff"


[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'nonce-{NONCE}' 'strict-dynamic' https://www.googletagmanager.com https://www.google-analytics.com https://www.youtube.com https://www.gstatic.com; object-src 'none'; base-uri 'self'; report-uri /csp-violation-report-endpoint;"